use_default_settings: true

general:
  instance_name: "Kuro Search"
  debug: false

search:
  safe_search: 0
  default_lang: "all"
  formats:
    - html
    - json

server:
  secret_key: "kuro-searxng-local-only"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false
